# ScrollIntel Heavy Volume Infrastructure
services:
  postgres:
    image: postgres:15-alpine
    container_name: scrollintel-postgres-hv
    environment:
      POSTGRES_DB: scrollintel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: scrollintel_password
      POSTGRES_SHARED_PRELOAD_LIBRARIES: pg_stat_statements
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_hv:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  redis:
    image: redis:7-alpine
    container_name: scrollintel-redis-hv
    ports:
      - "6379:6379"
    volumes:
      - redis_data_hv:/data
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 2G

  minio:
    image: minio/minio:latest
    container_name: scrollintel-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address ":9001"
    deploy:
      resources:
        limits:
          memory: 1G

  celery-worker:
    build: .
    container_name: scrollintel-celery-worker
    command: celery -A scrollintel.core.celery_app worker --loglevel=info --concurrency=4
    volumes:
      - ./scrollintel:/app/scrollintel
      - ./uploads:/app/uploads
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:scrollintel_password@postgres:5432/scrollintel
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  celery-beat:
    build: .
    container_name: scrollintel-celery-beat
    command: celery -A scrollintel.core.celery_app beat --loglevel=info
    volumes:
      - ./scrollintel:/app/scrollintel
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:scrollintel_password@postgres:5432/scrollintel
    depends_on:
      - postgres
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: scrollintel-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    container_name: scrollintel-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  postgres_data_hv:
  redis_data_hv:
  minio_data:
  prometheus_data:
  grafana_data:

networks:
  default:
    name: scrollintel-heavy-volume
