# ScrollIntel Minimal Docker Compose
services:
  postgres:
    image: postgres:15-alpine
    container_name: scrollintel-postgres
    environment:
      POSTGRES_DB: scrollintel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: scrollintel_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: scrollintel-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: scrollintel-network
