[phases.setup]
nixPkgs = ["python311", "pip", "gcc", "pkg-config"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements_railway.txt"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "python railway_deploy.py"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PORT = "8000"