# Alertmanager Configuration for ScrollIntel Launch MVP
# Handles alert routing, grouping, and notifications

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@scrollintel.com'
  smtp_auth_username: 'alerts@scrollintel.com'
  smtp_auth_password: 'your-smtp-password'

# Inhibition rules allow to mute a set of alerts given that another alert is firing
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'component']

# Route tree for alert notifications
route:
  group_by: ['alertname', 'component']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 5m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 30m
    - match:
        component: database
      receiver: 'database-alerts'
    - match:
        component: agents
      receiver: 'agent-alerts'

# Notification receivers
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://backend:8000/api/v1/alerts/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'ops-team@scrollintel.com'
        subject: '[CRITICAL] ScrollIntel Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Component: {{ .Labels.component }}
          Started: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-critical'
        title: 'Critical Alert: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        color: 'danger'
    webhook_configs:
      - url: 'http://backend:8000/api/v1/alerts/critical'
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: 'dev-team@scrollintel.com'
        subject: '[WARNING] ScrollIntel Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Component: {{ .Labels.component }}
          Started: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-warning'
        title: 'Warning Alert: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        color: 'warning'

  - name: 'database-alerts'
    email_configs:
      - to: 'dba-team@scrollintel.com'
        subject: '[DATABASE] ScrollIntel Alert: {{ .GroupLabels.alertname }}'
        body: |
          Database Alert Details:
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Database: {{ .Labels.database }}
          Started: {{ .StartsAt }}
          {{ end }}

  - name: 'agent-alerts'
    email_configs:
      - to: 'ai-team@scrollintel.com'
        subject: '[AGENTS] ScrollIntel Alert: {{ .GroupLabels.alertname }}'
        body: |
          Agent Alert Details:
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Agent Type: {{ .Labels.agent_type }}
          Started: {{ .StartsAt }}
          {{ end }}