# Prometheus configuration for ScrollIntel-G6
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules_g6.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # ScrollIntel-G6 main application
  - job_name: 'scrollintel-g6'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis cluster monitoring
  - job_name: 'redis-cluster'
    static_configs:
      - targets: 
        - 'redis-node-1:6379'
        - 'redis-node-2:6379'
        - 'redis-node-3:6379'
    metrics_path: '/metrics'

  # Kubernetes cluster monitoring
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
    - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: default;kubernetes;https

  # Kubernetes nodes
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
    - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: kubernetes.default.svc:443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics

  # Kubernetes pods
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name

  # Data Product Registry metrics
  - job_name: 'data-product-registry'
    static_configs:
      - targets: ['data-registry:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Agent Pool metrics
  - job_name: 'agent-pool'
    static_configs:
      - targets: 
        - 'code-agent:8002'
        - 'policy-agent:8003'
        - 'bi-agent:8004'
        - 'creative-agent:8005'
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Data Quality Agents
  - job_name: 'data-quality-agents'
    static_configs:
      - targets:
        - 'schema-drift-agent:8010'
        - 'anomaly-detection-agent:8011'
        - 'bias-monitoring-agent:8012'
    metrics_path: '/metrics'
    scrape_interval: 60s

  # Self-Improvement Engine
  - job_name: 'self-improvement-engine'
    static_configs:
      - targets: ['improvement-engine:8020']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # System infrastructure
  - job_name: 'node-exporter'
    static_configs:
      - targets: 
        - 'node-exporter:9100'
    scrape_interval: 15s

  # Database monitoring
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Elasticsearch monitoring
  - job_name: 'elasticsearch-exporter'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    scrape_interval: 30s

  # Neo4j monitoring (for lineage graph)
  - job_name: 'neo4j-exporter'
    static_configs:
      - targets: ['neo4j-exporter:7474']
    metrics_path: '/metrics'
    scrape_interval: 30s