apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-data-readiness-config
  namespace: ai-data-readiness
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  REDIS_URL: "redis://redis-service:6379/0"
  DATABASE_URL: "postgresql://postgres:password@postgres-service:5432/ai_data_readiness"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-data-readiness-secrets
  namespace: ai-data-readiness
type: Opaque
stringData:
  DATABASE_PASSWORD: "password"
  SECRET_KEY: "your-secret-key-here"
  JWT_SECRET: "your-jwt-secret-here"